version: '3'
services:
  frontend:
    image: frontend
    build: ./frontend
    ports:
      - 80:80
    networks:
      - private

  backend:
    image: backend
    build: ./backend
    env_file:
      - ./env_templates/env_backend
    networks:
      - private

  extractor:
    image: extractor
    build: ./extractor
    env_file:
      - ./env_templates/env_extractor
    networks:
      - private

  database:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
    command: mongod --bind_ip_all
    ports:
      - 27017:27017
    expose:
      - 27017
    networks:
      - private
    env_file:
      - ./env_templates/env_mongo

volumes:
  db-data:

networks:
  private:
